version: '2'
services:
    adap_gateway-app:
        image: adap_gateway
        external_links:
            - adap_gateway-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - adap_gateway-cassandra:cassandra
            - adap_gateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adap_gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    adap_gateway-postgresql:
        extends:
            file: postgresql.yml
            service: adap_gateway-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: adap_gateway-cassandra
    adap_gateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adap_gateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
