version: '2'
services:
    adap_gateway-cassandra:
        container_name: adap_gateway-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/adap_gateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    adap_gateway-cassandra-node:
        image: cassandra:2.2.5
        links:
            - adap_gateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    adap_gateway-cassandra-migration:
        container_name: adap_gateway-cassandra-migration
        links:
            - adap_gateway-cassandra
        environment:
            - CASSANDRA_CONTACT_POINT=adap_gateway-cassandra
        build:
            context: .
            dockerfile: cassandra/Cassandra.Dockerfile
        volumes:
            - ../resources/config/cql:/cql:ro
